<a href="https://colab.research.google.com/github/garthajon/QuantFinanceIntro/blob/main/TopUSDigitalStocks_MainStats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import yfinance as yf
import pandas as pd
from tabulate import tabulate
from datetime import datetime, timedelta

# Define 25 top digital/AI/social media-related stocks
tickers = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "TSLA", "CRM", "ADBE", "INTC",
    "AMD", "NFLX", "SNOW", "PLTR", "SHOP", "SQ", "PYPL", "UBER", "LYFT", "COIN",
    "NET", "DDOG", "ZS", "OKTA", "MDB", "ROKU", "DOCU", "TWLO", "FSLY", "AI",
    "SMCI", "ASML", "PANW", "CRWD", "ABNB", "BIDU", "TWTR", "AVGO", "TEAM", "NOW",
    "ORCL", "TCEHY", "SE", "RBLX", "WIX", "ZI", "DUOL", "ESTC", "BL", "AMPL"
]

# Time window
end_date = datetime.today()
start_date = end_date - timedelta(days=365)

results = []

for ticker in tickers:
    data = yf.download(ticker, start=start_date, end=end_date)

    if data.empty:
        continue

    close_prices = data['Close']
    current_price = close_prices.iloc[-1]
    high_52wk = close_prices.max()
    low_52wk = close_prices.min()
    avg_52wk = close_prices.mean()
    std_52wk = close_prices.std()

    near_high = current_price >= (0.60 * high_52wk)
    near_low = current_price <= (1.4 * low_52wk)
    print (near_high)
    print (near_low)


    if (1==1)  or (2==2):
        results.append({
            "Ticker": ticker,
            "Current Price": round(current_price, 2),
            "52W High": round(high_52wk, 2),
            "52W Low": round(low_52wk, 2),
            "52W Avg": round(avg_52wk, 2),
            "52W Std Dev": round(std_52wk, 2)
            #"Near": "High" if (near_high)  else "Low"
        })

# Display results
df = pd.DataFrame(results)
#df_sorted = df.sort_values(by="Near", ascending=False)

df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
AAPL    True
dtype: bool
Ticker
AAPL    True
dtype: bool
Ticker
MSFT    True
dtype: bool
Ticker
MSFT    True
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
GOOGL    True
dtype: bool
Ticker
GOOGL    True
dtype: bool
Ticker
AMZN    True
dtype: bool
Ticker
AMZN    True
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
META    True
dtype: bool
Ticker
META    False
dtype: bool
Ticker
NVDA    True
dtype: bool
Ticker
NVDA    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
TSLA    True
dtype: bool
Ticker
TSLA    False
dtype: bool
Ticker
CRM    True
dtype: bool
Ticker
CRM    True
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
ADBE    True
dtype: bool
Ticker
ADBE    True
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
INTC    False
dtype: bool
Ticker
INTC    True
dtype: bool
Ticker
AMD    True
dtype: bool
Ticker
AMD    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
NFLX    True
dtype: bool
Ticker
NFLX    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
SNOW    True
dtype: bool
Ticker
SNOW    False
dtype: bool
Ticker
PLTR    True
dtype: bool
Ticker
PLTR    False
dtype: bool
Ticker
SHOP    True
dtype: bool
Ticker
SHOP    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['SQ']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
PYPL    True
dtype: bool
Ticker
PYPL    True
dtype: bool
Ticker
UBER    True
dtype: bool
Ticker
UBER    False
dtype: bool
Ticker
LYFT    True
dtype: bool
Ticker
LYFT    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
COIN    True
dtype: bool
Ticker
COIN    False
dtype: bool
Ticker
NET    True
dtype: bool
Ticker
NET    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
DDOG    True
dtype: bool
Ticker
DDOG    True
dtype: bool
Ticker
ZS    True
dtype: bool
Ticker
ZS    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
OKTA    True
dtype: bool
Ticker
OKTA    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
MDB    False
dtype: bool
Ticker
MDB    True
dtype: bool
Ticker
ROKU    True
dtype: bool
Ticker
ROKU    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
DOCU    True
dtype: bool
Ticker
DOCU    False
dtype: bool
Ticker
TWLO    True
dtype: bool
Ticker
TWLO    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
FSLY    True
dtype: bool
Ticker
FSLY    False
dtype: bool
Ticker
AI    True
dtype: bool
Ticker
AI    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
SMCI    False
dtype: bool
Ticker
SMCI    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
ASML    True
dtype: bool
Ticker
ASML    True
dtype: bool
Ticker
PANW    True
dtype: bool
Ticker
PANW    True
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
CRWD    True
dtype: bool
Ticker
CRWD    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
ABNB    True
dtype: bool
Ticker
ABNB    True
dtype: bool
Ticker
BIDU    True
dtype: bool
Ticker
BIDU    True
dtype: bool

[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['TWTR']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
AVGO    True
dtype: bool
Ticker
AVGO    False
dtype: bool

Ticker
TEAM    True
dtype: bool
Ticker
TEAM    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
NOW    True
dtype: bool
Ticker
NOW    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
ORCL    True
dtype: bool
Ticker
ORCL    False
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
TCEHY    True
dtype: bool
Ticker
TCEHY    True
dtype: bool
Ticker
SE    True
dtype: bool
Ticker
SE    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
RBLX    True
dtype: bool
Ticker
RBLX    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
WIX    True
dtype: bool
Ticker
WIX    True
dtype: bool

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Ticker
ZI    True
dtype: bool
Ticker
ZI    True
dtype: bool
Ticker
DUOL    True
dtype: bool
Ticker
DUOL    False
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
ESTC    True
dtype: bool
Ticker
ESTC    True
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
BL    True
dtype: bool
Ticker
BL    True
dtype: bool

[*********************100%***********************]  1 of 1 completed

Ticker
AMPL    True
dtype: bool
Ticker
AMPL    False
dtype: bool

,Ticker,Current Price,52W High,52W Low,52W Avg,52W Std Dev
0,AAPL,Ticker AAPL 200.85 Name: 2025-05-30 00:00:0...,Ticker AAPL 258.4 dtype: float64,Ticker AAPL 172.19 dtype: float64,Ticker AAPL 222.97 dtype: float64,Ticker AAPL 15.38 dtype: float64
1,MSFT,Ticker MSFT 460.36 Name: 2025-05-30 00:00:0...,Ticker MSFT 464.0 dtype: float64,Ticker MSFT 353.91 dtype: float64,Ticker MSFT 418.79 dtype: float64,Ticker MSFT 22.88 dtype: float64
2,GOOGL,Ticker GOOGL 171.74 Name: 2025-05-30 00:00:...,Ticker GOOGL 206.14 dtype: float64,Ticker GOOGL 144.7 dtype: float64,Ticker GOOGL 171.93 dtype: float64,Ticker GOOGL 13.24 dtype: float64
3,AMZN,Ticker AMZN 205.01 Name: 2025-05-30 00:00:0...,Ticker AMZN 242.06 dtype: float64,Ticker AMZN 161.02 dtype: float64,Ticker AMZN 198.05 dtype: float64,Ticker AMZN 19.0 dtype: float64
4,META,Ticker META 647.49 Name: 2025-05-30 00:00:0...,Ticker META 736.02 dtype: float64,Ticker META 452.21 dtype: float64,Ticker META 573.32 dtype: float64,Ticker META 63.04 dtype: float64
5,NVDA,Ticker NVDA 135.13 Name: 2025-05-30 00:00:0...,Ticker NVDA 149.42 dtype: float64,Ticker NVDA 94.31 dtype: float64,Ticker NVDA 125.39 dtype: float64,Ticker NVDA 12.74 dtype: float64
6,TSLA,Ticker TSLA 346.46 Name: 2025-05-30 00:00:0...,Ticker TSLA 479.86 dtype: float64,Ticker TSLA 170.66 dtype: float64,Ticker TSLA 284.1 dtype: float64,Ticker TSLA 75.23 dtype: float64
7,CRM,Ticker CRM 265.37 Name: 2025-05-30 00:00:00...,Ticker CRM 366.87 dtype: float64,Ticker CRM 227.7 dtype: float64,Ticker CRM 285.35 dtype: float64,Ticker CRM 36.03 dtype: float64
8,ADBE,Ticker ADBE 415.09 Name: 2025-05-30 00:00:0...,Ticker ADBE 586.55 dtype: float64,Ticker ADBE 340.0 dtype: float64,Ticker ADBE 473.23 dtype: float64,Ticker ADBE 65.23 dtype: float64
9,INTC,Ticker INTC 19.55 Name: 2025-05-30 00:00:00...,Ticker INTC 34.65 dtype: float64,Ticker INTC 18.13 dtype: float64,Ticker INTC 23.28 dtype: float64,Ticker INTC 4.18 dtype: float64
10,AMD,Ticker AMD 110.73 Name: 2025-05-30 00:00:00...,Ticker AMD 183.96 dtype: float64,Ticker AMD 78.21 dtype: float64,Ticker AMD 132.19 dtype: float64,Ticker AMD 24.93 dtype: float64
11,NFLX,Ticker NFLX 1207.23 Name: 2025-05-30 00:00:...,Ticker NFLX 1211.57 dtype: float64,Ticker NFLX 598.55 dtype: float64,Ticker NFLX 843.75 dtype: float64,Ticker NFLX 165.84 dtype: float64
12,SNOW,Ticker SNOW 205.67 Name: 2025-05-30 00:00:0...,Ticker SNOW 206.35 dtype: float64,Ticker SNOW 108.56 dtype: float64,Ticker SNOW 146.45 dtype: float64,Ticker SNOW 26.13 dtype: float64
13,PLTR,Ticker PLTR 131.78 Name: 2025-05-30 00:00:0...,Ticker PLTR 131.78 dtype: float64,Ticker PLTR 21.32 dtype: float64,Ticker PLTR 63.99 dtype: float64,Ticker PLTR 32.48 dtype: float64
14,SHOP,Ticker SHOP 107.22 Name: 2025-05-30 00:00:0...,Ticker SHOP 129.31 dtype: float64,Ticker SHOP 52.26 dtype: float64,Ticker SHOP 89.89 dtype: float64,Ticker SHOP 19.63 dtype: float64
15,PYPL,Ticker PYPL 70.28 Name: 2025-05-30 00:00:00...,Ticker PYPL 91.81 dtype: float64,Ticker PYPL 57.22 dtype: float64,Ticker PYPL 73.47 dtype: float64,Ticker PYPL 10.03 dtype: float64
16,UBER,Ticker UBER 84.16 Name: 2025-05-30 00:00:00...,Ticker UBER 92.46 dtype: float64,Ticker UBER 58.48 dtype: float64,Ticker UBER 72.63 dtype: float64,Ticker UBER 6.82 dtype: float64
17,LYFT,Ticker LYFT 15.24 Name: 2025-05-30 00:00:00...,Ticker LYFT 18.59 dtype: float64,Ticker LYFT 9.08 dtype: float64,Ticker LYFT 13.38 dtype: float64,Ticker LYFT 1.9 dtype: float64
18,COIN,Ticker COIN 246.62 Name: 2025-05-30 00:00:0...,Ticker COIN 343.62 dtype: float64,Ticker COIN 147.35 dtype: float64,Ticker COIN 228.45 dtype: float64,Ticker COIN 46.87 dtype: float64
19,NET,Ticker NET 165.89 Name: 2025-05-30 00:00:00...,Ticker NET 176.5 dtype: float64,Ticker NET 67.43 dtype: float64,Ticker NET 104.96 dtype: float64,Ticker NET 26.84 dtype: float64
20,DDOG,Ticker DDOG 117.88 Name: 2025-05-30 00:00:0...,Ticker DDOG 168.65 dtype: float64,Ticker DDOG 87.0 dtype: float64,Ticker DDOG 122.14 dtype: float64,Ticker DDOG 17.02 dtype: float64
21,ZS,"Ticker ZS 275.7 Name: 2025-05-30 00:00:00, ...",Ticker ZS 275.7 dtype: float64,Ticker ZS 155.9 dtype: float64,Ticker ZS 196.07 dtype: float64,Ticker ZS 20.29 dtype: float64
22,OKTA,Ticker OKTA 103.17 Name: 2025-05-30 00:00:0...,Ticker OKTA 127.3 dtype: float64,Ticker OKTA 71.0 dtype: float64,Ticker OKTA 91.2 dtype: float64,Ticker OKTA 14.17 dtype: float64
23,MDB,Ticker MDB 188.83 Name: 2025-05-30 00:00:00...,Ticker MDB 350.13 dtype: float64,Ticker MDB 145.85 dtype: float64,Ticker MDB 244.93 dtype: float64,Ticker MDB 44.63 dtype: float64
24,ROKU,Ticker ROKU 72.46 Name: 2025-05-30 00:00:00...,Ticker ROKU 99.07 dtype: float64,Ticker ROKU 51.67 dtype: float64,Ticker ROKU 70.45 dtype: float64,Ticker ROKU 9.79 dtype: float64
25,DOCU,Ticker DOCU 88.61 Name: 2025-05-30 00:00:00...,Ticker DOCU 106.99 dtype: float64,Ticker DOCU 49.73 dtype: float64,Ticker DOCU 73.74 dtype: float64,Ticker DOCU 15.21 dtype: float64
26,TWLO,Ticker TWLO 117.7 Name: 2025-05-30 00:00:00...,Ticker TWLO 148.35 dtype: float64,Ticker TWLO 53.02 dtype: float64,Ticker TWLO 88.47 dtype: float64,Ticker TWLO 26.68 dtype: float64
27,FSLY,"Ticker FSLY 7.28 Name: 2025-05-30 00:00:00,...",Ticker FSLY 11.34 dtype: float64,Ticker FSLY 5.0 dtype: float64,Ticker FSLY 7.58 dtype: float64,Ticker FSLY 1.44 dtype: float64
28,AI,"Ticker AI 26.59 Name: 2025-05-30 00:00:00, ...",Ticker AI 42.94 dtype: float64,Ticker AI 18.24 dtype: float64,Ticker AI 27.3 dtype: float64,Ticker AI 5.36 dtype: float64
29,SMCI,Ticker SMCI 40.02 Name: 2025-05-30 00:00:00...,Ticker SMCI 92.0 dtype: float64,Ticker SMCI 18.01 dtype: float64,Ticker SMCI 46.66 dtype: float64,Ticker SMCI 18.25 dtype: float64
30,ASML,Ticker ASML 736.77 Name: 2025-05-30 00:00:0...,Ticker ASML 1088.97 dtype: float64,Ticker ASML 593.68 dtype: float64,Ticker ASML 781.05 dtype: float64,Ticker ASML 119.02 dtype: float64
31,PANW,Ticker PANW 192.42 Name: 2025-05-30 00:00:0...,Ticker PANW 208.28 dtype: float64,Ticker PANW 145.04 dtype: float64,Ticker PANW 178.49 dtype: float64,Ticker PANW 13.54 dtype: float64
32,CRWD,Ticker CRWD 471.37 Name: 2025-05-30 00:00:0...,Ticker CRWD 472.22 dtype: float64,Ticker CRWD 217.89 dtype: float64,Ticker CRWD 347.56 dtype: float64,Ticker CRWD 59.35 dtype: float64
33,ABNB,Ticker ABNB 129.0 Name: 2025-05-30 00:00:00...,Ticker ABNB 161.42 dtype: float64,Ticker ABNB 105.69 dtype: float64,Ticker ABNB 132.33 dtype: float64,Ticker ABNB 11.21 dtype: float64
34,BIDU,"Ticker BIDU 81.9 Name: 2025-05-30 00:00:00,...",Ticker BIDU 115.13 dtype: float64,Ticker BIDU 76.86 dtype: float64,Ticker BIDU 89.45 dtype: float64,Ticker BIDU 6.28 dtype: float64
35,AVGO,Ticker AVGO 242.07 Name: 2025-05-30 00:00:0...,Ticker AVGO 248.58 dtype: float64,Ticker AVGO 130.59 dtype: float64,Ticker AVGO 184.08 dtype: float64,Ticker AVGO 29.87 dtype: float64
36,TEAM,Ticker TEAM 207.63 Name: 2025-05-30 00:00:0...,Ticker TEAM 322.94 dtype: float64,Ticker TEAM 137.41 dtype: float64,Ticker TEAM 212.42 dtype: float64,Ticker TEAM 47.09 dtype: float64
37,NOW,Ticker NOW 1011.09 Name: 2025-05-30 00:00:0...,Ticker NOW 1170.39 dtype: float64,Ticker NOW 656.93 dtype: float64,Ticker NOW 912.16 dtype: float64,Ticker NOW 123.6 dtype: float64
38,ORCL,Ticker ORCL 165.53 Name: 2025-05-30 00:00:0...,Ticker ORCL 191.27 dtype: float64,Ticker ORCL 115.9 dtype: float64,Ticker ORCL 155.83 dtype: float64,Ticker ORCL 18.53 dtype: float64
39,TCEHY,Ticker TCEHY 62.78 Name: 2025-05-30 00:00:0...,Ticker TCEHY 69.79 dtype: float64,Ticker TCEHY 45.07 dtype: float64,Ticker TCEHY 54.53 dtype: float64,Ticker TCEHY 6.79 dtype: float64
40,SE,"Ticker SE 160.37 Name: 2025-05-30 00:00:00,...",Ticker SE 165.24 dtype: float64,Ticker SE 59.94 dtype: float64,Ticker SE 104.99 dtype: float64,Ticker SE 26.34 dtype: float64
41,RBLX,Ticker RBLX 86.98 Name: 2025-05-30 00:00:00...,Ticker RBLX 86.98 dtype: float64,Ticker RBLX 33.62 dtype: float64,Ticker RBLX 53.1 dtype: float64,Ticker RBLX 12.83 dtype: float64
42,WIX,Ticker WIX 148.95 Name: 2025-05-30 00:00:00...,Ticker WIX 246.76 dtype: float64,Ticker WIX 146.5 dtype: float64,Ticker WIX 180.52 dtype: float64,Ticker WIX 27.4 dtype: float64
43,ZI,"Ticker ZI 9.55 Name: 2025-05-30 00:00:00, d...",Ticker ZI 13.08 dtype: float64,Ticker ZI 7.41 dtype: float64,Ticker ZI 10.42 dtype: float64,Ticker ZI 1.14 dtype: float64
44,DUOL,Ticker DUOL 519.61 Name: 2025-05-30 00:00:0...,Ticker DUOL 540.68 dtype: float64,Ticker DUOL 158.85 dtype: float64,Ticker DUOL 303.32 dtype: float64,Ticker DUOL 92.54 dtype: float64
45,ESTC,Ticker ESTC 80.87 Name: 2025-05-30 00:00:00...,Ticker ESTC 122.27 dtype: float64,Ticker ESTC 70.14 dtype: float64,Ticker ESTC 96.94 dtype: float64,Ticker ESTC 13.97 dtype: float64
46,BL,"Ticker BL 55.93 Name: 2025-05-30 00:00:00, ...",Ticker BL 65.64 dtype: float64,Ticker BL 42.27 dtype: float64,Ticker BL 53.04 dtype: float64,Ticker BL 6.18 dtype: float64
47,AMPL,Ticker AMPL 12.39 Name: 2025-05-30 00:00:00...,Ticker AMPL 14.44 dtype: float64,Ticker AMPL 7.71 dtype: float64,Ticker AMPL 9.96 dtype: float64,Ticker AMPL 1.55 dtype: float64